---
title: "Data Replication - Optimal Group Size in a Highly Social Animal"
author: "Frank Short"
date: "12/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading

```{r Loading}
library(curl)
f <- curl("https://raw.githubusercontent.com/fshortIV/fshortIV-data-replication-assignment/main/fGC%20and%20daily%20travel%20distance%20data.csv?token=AVR3CJ6WHKQWB2CHR7IA4E3BWEKMA")
fgcdata <- read.csv(f, header = TRUE, sep = ",", stringsAsFactors = FALSE)
names(fgcdata)<-c('ID','FGC',"DTD","LogFGC")
colnames(fgcdata)
head(fgcdata)

d <- curl("https://raw.githubusercontent.com/fshortIV/fshortIV-data-replication-assignment/main/Annual%20home%20range%20and%20foraging%20predictors.csv?token=AVR3CJ2FA5VGOVLFGFPDH4TBWEKO2")
annualdata <- read.csv(d, header = TRUE, sep = ",", stringsAsFactors = FALSE)
colnames(annualdata)
head(annualdata)

g <- curl("https://raw.githubusercontent.com/fshortIV/fshortIV-data-replication-assignment/main/Monthly%20ranging%20pattern%20predictors.csv?token=AVR3CJZF3XMEKNFOKPVVXEDBWEKRU")
monthlyhrdata <- read.csv(g, header = TRUE, sep = ",", stringsAsFactors = FALSE)
colnames(monthlyhrdata)
head(monthlyhrdata)

h <- curl("https://raw.githubusercontent.com/fshortIV/fshortIV-data-replication-assignment/main/Monthly%20fGC%20predictors.csv?token=AVR3CJ32CHTB7RO55QBQM6LBWEKUE")
monthlyfgcdata <- read.csv(h, header = TRUE, sep = ",", stringsAsFactors = FALSE)
colnames(monthlyfgcdata)
head(monthlyfgcdata)

```
## Preliminary Data Visualization

```{r Data Visualization}
library(ggplot2)

groupsize1 <- ggplot(data = annualdata, aes(x = Average.group.size, y = Annual.home.range.size..sq.km.))
groupsize1 <- groupsize1 + geom_point() 
groupsize1 <- groupsize1 + stat_smooth(method = "lm", formula = y ~ x + I(x^2), size = 1)
groupsize1

groupsize2 <- ggplot(data = monthlyhrdata, aes(x = Group.size, y = Monthly.home.range.size..sq.km.))
groupsize2 <- groupsize1 + geom_point() 
groupsize2 <- groupsize1 + stat_smooth(method = "lm", formula = y ~ x + I(x^2), size = 1)
groupsize2

groupsize3 <- ggplot(data = monthlyhrdata, aes(x = Group.size, y = Average.daily.travel..km.))
groupsize3 <- groupsize3 + geom_point() 
groupsize3 <- groupsize3 + stat_smooth(method = "lm", formula = y ~ x + I(x^2), size = 1)
groupsize3

groupsize4 <- ggplot(data = monthlyhrdata, aes(x = Group.size, y = Evenness.of.space.use))
groupsize4 <- groupsize4 + geom_point() 
groupsize4 <- groupsize4 + stat_smooth(method = "lm", formula = y ~ x + I(x^2), size = 1)
groupsize4

groupsize5 <- ggplot(data = monthlyfgcdata, aes(x = Group.size, y = fGC..g.ng.dry.feces.))
groupsize5 <- groupsize5 + geom_point() 
groupsize5 <- groupsize5 + stat_smooth(method = "lm", formula = y ~ x + I(x^2), size = 1)
groupsize5



```
## Linear Models



```{r Linear Model FGC}
library(ggplot2)

lm<- lm(LogFGC ~ DTD, data = fgcdata)
summary(lm)

lm <- ggplot(data = fgcdata, aes(x = DTD, y = LogFGC))
lm<- lm + geom_point() 
lm<- lm + geom_smooth(method = "lm", formula = y ~ x) + xlab("Daily Travel Distance (km)") + ylab("Log Fecal Glucocorticoid (ng/g dry feces)") + theme_classic() + xlim(3, 9) + ylim(1.6, 2.4) + geom_text(x=6, y=2.375, label="y = 0.02x + 1.80", size=3.5)
lm
```

```{r Linear Model Foraging}
lm2<- lm(Proportion.time.foraging ~ Average.group.size, data = annualdata)
summary(lm2)

lm <- ggplot(data = annualdata, aes(x = Average.group.size, y = Proportion.time.foraging))
lm<- lm + geom_point() 
lm<- lm + geom_smooth(method = "lm", formula = y ~ x) + xlab("Group Size") + ylab("Proportion time spent foraging") + theme_classic() + xlim(10, 110) + ylim(0.50, 0.85) + geom_text(x=61, y=0.8375, label="y = 0.002x + 0.609", size=3.5)
lm
```

```{r GEE Analysis}
library(gee)
library(geepack)


geeAnnual<-  geeglm(formula = log(Annual.home.range.size..sq.km.) ~ Average.group.size + I(Average.group.size^2) + Cumulative.rainfall..mm. + Rainfall.evenness + Average.maximum.temperature..degrees.C., id = X.U.FEFF.Group.ID, data = annualdata, corstr = "ar1")
summary(geeAnnual)

geeMonthlyHr<-  geeglm(formula = log(Monthly.home.range.size..sq.km.) ~ Group.size + I(Group.size^2) + Cumulative.rainfall..mm. + Average.maximum.temperature..degrees.C., id = X.U.FEFF.Group.ID, data = monthlyhrdata,
corstr = "ar1")
summary(geeMonthlyHr)

geeMonthlyDT<-  geeglm(formula = log(Average.daily.travel..km.) ~ Group.size + I(Group.size^2) + Cumulative.rainfall..mm. + Average.maximum.temperature..degrees.C., id = X.U.FEFF.Group.ID, data = monthlyhrdata,
corstr = "ar1")
summary(geeMonthlyDT)

geeMonthlyEvenness<-  geeglm(formula = Evenness.of.space.use ~ Group.size + I(Group.size^2) + Cumulative.rainfall..mm. + Average.maximum.temperature..degrees.C., id = X.U.FEFF.Group.ID, data = monthlyhrdata,
corstr = "ar1")
summary(geeMonthlyEvenness)

geeMonthlyFGC<-  geeglm(formula = log(fGC..g.ng.dry.feces.) ~ Group.size + I(Group.size^2) + Cumulative.rainfall..mm. + Average.maximum.temperature..degrees.C., id = X.U.FEFF.Group.ID, data = monthlyfgcdata,
corstr = "ar1")
summary(geeMonthlyFGC)

```

```{r GEE Table}
Estimate = c(geeAnnual$coefficients[1],geeAnnual$coefficients[2],geeAnnual$coefficients[3],geeAnnual$coefficients[4],geeAnnual$coefficients[5],geeAnnual$coefficients[6])
Estimate = as.numeric(Estimate)
Estimate <- format(Estimate, digits=3)


EstimateHr = c(geeMonthlyHr$coefficients[1],geeMonthlyHr$coefficients[2],geeMonthlyHr$coefficients[3],geeMonthlyHr$coefficients[4],geeMonthlyHr$coefficients[5])
EstimateHr = formatC(EstimateHr, format = "e", digits = 3)

EstimateDT = c(geeMonthlyDT$coefficients[1],geeMonthlyDT$coefficients[2],geeMonthlyDT$coefficients[3],geeMonthlyDT$coefficients[4],geeMonthlyDT$coefficients[5])
EstimateDT = formatC(EstimateDT, format = "e", digits = 3)

EstimateEven = c(geeMonthlyEvenness$coefficients[1],geeMonthlyEvenness$coefficients[2],geeMonthlyEvenness$coefficients[3],geeMonthlyEvenness$coefficients[4],geeMonthlyEvenness$coefficients[5])
EstimateEven = formatC(EstimateEven, format = "e", digits = 3)

EstimateFGC = c(geeMonthlyFGC$coefficients[1],geeMonthlyFGC$coefficients[2],geeMonthlyFGC$coefficients[3],geeMonthlyFGC$coefficients[4],geeMonthlyFGC$coefficients[5])
EstimateFGC = formatC(EstimateFGC, format = "e", digits = 3)

Wald = c(summary(geeAnnual)$coefficients[1,3],summary(geeAnnual)$coefficients[2,3],summary(geeAnnual)$coefficients[3,3],summary(geeAnnual)$coefficients[4,3],summary(geeAnnual)$coefficients[5,3],summary(geeAnnual)$coefficients[6,3])
Wald = as.numeric(Wald)
Wald <- format(Wald, digits=3)

WaldHR = c(summary(geeMonthlyHr)$coefficients[1,3],summary(geeMonthlyHr)$coefficients[2,3],summary(geeMonthlyHr)$coefficients[3,3],summary(geeMonthlyHr)$coefficients[4,3],summary(geeMonthlyHr)$coefficients[5,3])
WaldHR = as.numeric(WaldHR)
WaldHR <- format(WaldHR, digits=3)

WaldDT = c(summary(geeMonthlyDT)$coefficients[1,3],summary(geeMonthlyDT)$coefficients[2,3],summary(geeMonthlyDT)$coefficients[3,3],summary(geeMonthlyDT)$coefficients[4,3],summary(geeMonthlyDT)$coefficients[5,3])
WaldDT = as.numeric(WaldDT)
WaldDT <- format(WaldDT, digits=3)

WaldEven = c(summary(geeMonthlyEvenness)$coefficients[1,3],summary(geeMonthlyEvenness)$coefficients[2,3],summary(geeMonthlyEvenness)$coefficients[3,3],summary(geeMonthlyEvenness)$coefficients[4,3],summary(geeMonthlyEvenness)$coefficients[5,3])
WaldEven = as.numeric(WaldEven)
WaldEven <- format(WaldEven, digits=3)

WaldFGC = c(summary(geeMonthlyFGC)$coefficients[1,3],summary(geeMonthlyFGC)$coefficients[2,3],summary(geeMonthlyFGC)$coefficients[3,3],summary(geeMonthlyFGC)$coefficients[4,3],summary(geeMonthlyFGC)$coefficients[5,3])
WaldFGC = as.numeric(WaldFGC)
WaldFGC <- format(WaldFGC, digits=3)


P = c(summary(geeAnnual)$coefficients[1,4],summary(geeAnnual)$coefficients[2,4],summary(geeAnnual)$coefficients[3,4],summary(geeAnnual)$coefficients[4,4],summary(geeAnnual)$coefficients[5,4],summary(geeAnnual)$coefficients[6,4])
P = as.numeric(P)
P <- format(P, digits=3)
P <- c("0.053","0.049","0.011","0.740","0.019","0.336")

PHR = c(summary(geeMonthlyHr)$coefficients[1,4],summary(geeMonthlyHr)$coefficients[2,4],summary(geeMonthlyHr)$coefficients[3,4],summary(geeMonthlyHr)$coefficients[4,4],summary(geeMonthlyHr)$coefficients[5,4])
PHR = c(formatC(PHR[1:3], format = "g", digits = 3), formatC(PHR[4:5], format = "f", digits = 3))
PHR[1:3] = "<0.001"

PDT = c(summary(geeMonthlyDT)$coefficients[1,4],summary(geeMonthlyDT)$coefficients[2,4],summary(geeMonthlyDT)$coefficients[3,4],summary(geeMonthlyDT)$coefficients[4,4],summary(geeMonthlyDT)$coefficients[5,4])
PDT = c(formatC(PDT[1], format = "g", digits=3),formatC(PDT[2:5], format = "f", digits=3))
PDT[1] = "<0.001"

PEven = c(summary(geeMonthlyEvenness)$coefficients[1,4],summary(geeMonthlyEvenness)$coefficients[2,4],summary(geeMonthlyEvenness)$coefficients[3,4],summary(geeMonthlyEvenness)$coefficients[4,4],summary(geeMonthlyEvenness)$coefficients[5,4])
PEven = c(formatC(PEven[1:3], format = "g", digits=3),formatC(PEven[4:5], format = "f", digits=3))
PEven[1:3] = "<0.001"

PGC = c(summary(geeMonthlyFGC)$coefficients[1,4],summary(geeMonthlyFGC)$coefficients[2,4],summary(geeMonthlyFGC)$coefficients[3,4],summary(geeMonthlyFGC)$coefficients[4,4],summary(geeMonthlyFGC)$coefficients[5,4])
PGC[1:3] = "<0.001"
PGC[4] = "0.207"
PGC[5] = "0.557"


library(kableExtra)
GEETable <- data.frame( 
  Dependent_Variable = c("Home range (annual)","Intercept","Group size","Group size^2","Cumulative rainfall","Rainfall evenness","Average maximum temperature","Home range (monthly)","Intercept","Group size","Group size^2","Cumulative rainfall","Average maximum temperature","Average daily distance traveled (monthly)","Intercept","Group size","Group size^2","Cumulative rainfall","Average maximum temperature","Evenness of space use (monthly)","Intercept","Group size","Group size^2","Cumulative rainfall","Average maximum temperature","Fecal glucocorticoids (monthly)","Intercept","Group size","Group size^2","Cumulative rainfall","Average maximum temperature") ,
  Estimate = c("",Estimate,"",EstimateHr,"",EstimateDT,"",EstimateEven,"",EstimateFGC),
  Wald = c("",Wald,"",WaldHR,"",WaldDT,"",WaldEven,"",WaldFGC),
  P = c("",P,"",PHR,"",PDT,"",PEven,"",PGC)
)

GeeKable<- GEETable %>%
  kbl(caption = "Results from GEEs") %>%
  kable_classic(full_width = F, html_font = "Cambria")
row_spec(GeeKable, row=c(3,4,6,10,11,16,17,22,23,28,29), bold = TRUE)


  
  
```

```{r GEE Plotting}
library(gridExtra)
AnnualPlotlm<- lm(Annual.home.range.size..sq.km. ~ Average.group.size + I(Average.group.size^2), data = annualdata)
summary(AnnualPlot)
# I did it!! Note: They do not explain AT ALL how their plots were generated like this.

AnnualPlot <- ggplot(data = annualdata, aes(x = Average.group.size, y = Annual.home.range.size..sq.km.))
AnnualPlot <- AnnualPlot + stat_smooth(method = "lm", formula = y ~ x + I(x^2), fullrange=TRUE) + xlab("Group Size") + ylab("Home Range Size") + theme_classic() + xlim(10, 110) + annotate("text",x=60, y=30, label="Annual: y = 0.003x^2 - 0.346x + 22.539", size=3.5) 
AnnualPlot

MonthlyPlotlm<- lm(Monthly.home.range.size..sq.km. ~ Group.size + I(Group.size^2), data = monthlyhrdata)
summary(MonthlyPlotlm)

MonthlyPlot <- ggplot(data = monthlyhrdata, aes(x = Group.size, y = Monthly.home.range.size..sq.km.))
MonthlyPlot <- MonthlyPlot + stat_smooth(method = "lm", formula = y ~ x + I(x^2), fullrange=TRUE) + xlab("Group Size") + ylab("Monthly Home Range Size") + theme_classic() + xlim(10, 110) + annotate("text",x=60, y=22.5, label="Monthly: y = 0.004x^2 - 0.417x + 20.019", size=3.5)
MonthlyPlot

BothPlot <- AnnualPlot + stat_smooth(aes(x = Group.size, y = Monthly.home.range.size..sq.km.), data = monthlyhrdata, 
              method = "lm", formula = y ~ x + I(x^2), fullrange=TRUE, color = "red")
BothPlot <- BothPlot +  annotate("text",x=60, y=28, label="Monthly: y = 0.004x^2 - 0.417x + 20.019", size=3.5) + annotate("text",x=60, y=17, label="Annual", size=4) + annotate("text", x=80, y=7, label="Monthly", size=4)
BothPlot

DailyTravelPlotlm<- lm(Average.daily.travel..km. ~ Group.size + I(Group.size^2), data = monthlyhrdata)
summary(DailyTravelPlotlm)

DailyTravelPlot <- ggplot(data = monthlyhrdata, aes(x = Group.size, y = Average.daily.travel..km.))
DailyTravelPlot <- DailyTravelPlot + stat_smooth(method = "lm", formula = y ~ x + I(x^2),fullrange=TRUE) + xlab("Group Size") + ylab("Daily Travel Distance (km)") + theme_classic() + annotate("text",x=60.5, y=6.4, label="Monthly: y = 0.000475x^2 - 0.056x + 6.249", size=3.5) + annotate("text",x=60, y=5.2, label="Monthly", size=4) + xlim(10,110)
DailyTravelPlot

EvennessPlotlm<- lm(Evenness.of.space.use ~ Group.size + I(Group.size^2), data = monthlyhrdata)
summary(EvennessPlotlm)

EvennessPlot <- ggplot(data = monthlyhrdata, aes(x = Group.size, y = Evenness.of.space.use))
EvennessPlot <- EvennessPlot + stat_smooth(method = "lm", formula = y ~ x + I(x^2), fullrange=TRUE) + xlab("Group Size") + ylab("Evenness of space use") + theme_classic() + annotate("text",x=60, y=4.9, label="Monthly: y = 0.0002x^2 - 0.020x + 4.710", size=3.5) + annotate("text", x=60, y=4.35, label="Monthly", size=4) + xlim(10,110)
EvennessPlot

FGCPlotlm<- lm(fGC..g.ng.dry.feces. ~ Group.size + I(Group.size^2), data = monthlyfgcdata)
summary(FGCPlotlm)

FGCPlot <- ggplot(data = monthlyfgcdata, aes(x = Group.size, y = fGC..g.ng.dry.feces.))
FGCPlot <- FGCPlot + stat_smooth(method = "lm", formula = y ~ x + I(x^2), fullrange=TRUE) + xlab("Group Size") + ylab("Fecal glucocorticoid (ng/g dry feces)") + theme_classic() + annotate("text",x=60, y=97, label="Monthly: y = 0.006x^2 - 0.785x + 97.314", size=3.5) + xlim(10,110)+annotate("text", x=60, y=81.5, label="Monthly", size=4)
FGCPlot

grid.arrange(BothPlot, DailyTravelPlot, EvennessPlot, FGCPlot, nrow = 2)
```
